/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // Safelist ensures these dynamically created classes are generated by Tailwind
  safelist: [
    {
      pattern: /bg-(blue|red|gray|green|yellow|purple|pink)-(100|200|500|600|900)/,
    },
    {
      pattern: /text-(blue|red|gray|green|yellow|purple|pink)-(600|800)/,
    },
    {
      pattern: /from-(blue|red|gray|green|yellow|purple|pink)-50/,
    },
    {
      pattern: /ring-(blue|red|gray|green|yellow|purple|pink)-(100|400|500)/,
    },
    {
      pattern: /peer-checked:bg-(blue|red|gray|green|yellow|purple|pink)-500/,
    },
    {
        pattern: /peer-checked:ring-(blue|red|gray|green|yellow|purple|pink)-400/,
    },
    'bg-gray-800', // For black theme button
  ],
  theme: {
    extend: {
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
      },
    },
  },
  plugins: [],
}